/* ═══════════════════════════════════════════════════
   WHITE CAT · TOOL LIBRARY
   scripts/tools/tool-library.js
   ═══════════════════════════════════════════════════ */

window.TOOL_CATEGORIES = [
  {
    id: 'os',
    label: 'Operating Systems & ISOs',
    icon: 'assets/tool/category/os.svg',
    color: 'gold',
    desc: 'Windows ISOs, system builds and core OS tools.'
  },
  {
    id: 'audio-video',
    label: 'Audio & Video Editors',
    icon: 'assets/tool/category/audio-video.svg',
    color: 'blue',
    desc: 'Professional audio editing, video production and export tools.'
  },
  {
    id: 'art-design',
    label: 'Art, Design & 3D',
    icon: 'assets/tool/category/art-design.svg',
    color: 'green',
    desc: 'Pixel art, illustration, graphic design and 3D modelling tools.'
  },
  {
    id: 'dev-coding',
    label: 'Development & Coding',
    icon: 'assets/tool/category/dev-coding.svg',
    color: 'blue',
    desc: 'Code editors, runtimes, compilers and developer utilities.'
  },
  {
    id: 'utilities',
    label: 'Utilities & Drivers',
    icon: 'assets/tool/category/utilities.svg',
    color: 'gold',
    desc: 'File tools, media players, browsers, codecs and system drivers.'
  },
  {
    id: 'pc-security',
    label: 'PC Performance & Security',
    icon: 'assets/tool/category/pc-security.svg',
    color: 'red',
    desc: 'Antivirus, boosters, RAM tools and PC optimisation software.'
  },
  {
    id: 'office-apps',
    label: 'Student, Office & Apps',
    icon: 'assets/tool/category/office-apps.svg',
    color: 'green',
    desc: 'Office suites, education apps, messaging and productivity tools.'
  }
];

window.TOOL_CATALOG = [

  /* ─── OPERATING SYSTEMS & ISOs ─── */
  {
    id: 'windows10',
    category: 'os',
    name: 'Windows 10',
    version: '22H2 / Tiny10 23H2',
    icon: 'assets/tool/software/os/windows10.png',
    desc: 'The most widely used Windows OS. Includes the standard 22H2 build and the lightweight Tiny10 23H2 edition — perfect for older or low-spec PCs that need a fast, lean system.',
    tags: ['OS', 'ISO', '64-bit'],
    tagsBlue: ['Lightweight Build'],
    price: 'Rs. 250',
    recommended: true,
    link: '',
    linkLabel: 'Get ISO'
  },
  {
    id: 'windows7',
    category: 'os',
    name: 'Windows 7',
    version: 'Ultimate SP1',
    icon: 'assets/tool/software/os/windows7.png',
    desc: 'Classic Windows 7 Ultimate with Service Pack 1. Legacy system for older hardware or nostalgia builds. No longer receives updates but runs stable on compatible machines.',
    tags: ['OS', 'ISO', 'Legacy'],
    tagsBlue: ['SP1'],
    price: 'Rs. 150',
    recommended: false,
    link: '',
    linkLabel: 'Get ISO'
  },
  {
    id: 'msoffice',
    category: 'os',
    name: 'Microsoft Office',
    version: '2024 LTSC (64-bit)',
    icon: 'assets/tool/software/os/msoffice.png',
    desc: 'The full Microsoft Office 2024 LTSC suite — Word, Excel, PowerPoint, Outlook and more. Long-Term Servicing Channel build for stable, update-free professional use.',
    tags: ['Office', 'LTSC', '64-bit'],
    tagsBlue: ['Word', 'Excel', 'PowerPoint'],
    price: 'Rs. 300',
    recommended: true,
    link: '',
    linkLabel: 'Get Office'
  },

  /* ─── AUDIO & VIDEO EDITORS ─── */
  {
    id: 'audition',
    category: 'audio-video',
    name: 'Adobe Audition',
    version: 'v25.0 (2025)',
    icon: 'assets/tool/software/audio-video/audition.png',
    desc: 'Industry-standard professional audio workstation by Adobe. Multitrack recording, audio restoration, mixing and mastering. Perfect for podcasts, music production and film sound.',
    tags: ['Audio', 'Adobe', 'Pro'],
    tagsBlue: ['Multitrack', 'Mastering'],
    price: 'Rs. 400',
    recommended: true,
    link: '',
    linkLabel: 'Get Tool'
  },
  {
    id: 'audacity',
    category: 'audio-video',
    name: 'Audacity',
    version: 'v4.0.0',
    icon: 'assets/tool/software/audio-video/audacity.png',
    desc: 'Free, open-source audio editor and recorder. Great for beginners and pros alike — trim, mix, apply effects, remove noise and export in multiple formats.',
    tags: ['Audio', 'Free', 'Open Source'],
    tagsBlue: ['Recording'],
    price: 'Free',
    recommended: false,
    link: 'https://www.audacityteam.org/download/',
    linkLabel: 'Official Site'
  },
  {
    id: 'capcut',
    category: 'audio-video',
    name: 'CapCut',
    version: 'v5.6.0',
    icon: 'assets/tool/software/audio-video/capcut.png',
    desc: 'Popular all-in-one video editor by ByteDance. Easy timeline editing, built-in effects, auto captions, speed ramps and templates. Great for social media content creation.',
    tags: ['Video', 'Desktop'],
    tagsBlue: ['Social Media', 'Templates'],
    price: 'Rs. 200',
    recommended: false,
    link: '',
    linkLabel: 'Get Tool'
  },
  {
    id: 'davinci',
    category: 'audio-video',
    name: 'DaVinci Resolve Studio',
    version: 'v19.1.3',
    icon: 'assets/tool/software/audio-video/davinci.png',
    desc: 'Hollywood-grade video editor with professional colour grading, Fairlight audio, Fusion VFX and full post-production pipeline. The Studio version unlocks all premium features.',
    tags: ['Video', 'Studio', 'Pro'],
    tagsBlue: ['Color Grading', 'VFX'],
    price: 'Rs. 500',
    recommended: true,
    link: 'https://www.blackmagicdesign.com/products/davinciresolve',
    linkLabel: 'Official Site'
  },
  {
    id: 'openshot',
    category: 'audio-video',
    name: 'OpenShot',
    version: 'v3.4.0',
    icon: 'assets/tool/software/audio-video/openshot.png',
    desc: 'Simple, free and open-source video editor with a clean interface. Drag-and-drop timeline, transitions, effects and supports dozens of video formats. Ideal for beginners.',
    tags: ['Video', 'Free', 'Open Source'],
    tagsBlue: ['Beginner Friendly'],
    price: 'Free',
    recommended: false,
    link: 'https://www.openshot.org/download/',
    linkLabel: 'Official Site'
  },

  /* ─── ART, DESIGN & 3D ─── */
  {
    id: 'aseprite',
    category: 'art-design',
    name: 'Aseprite',
    version: 'Latest (ZIP)',
    icon: 'assets/tool/software/art-design/aseprite.png',
    desc: 'The go-to pixel art and animation tool. Frame-by-frame animation, onion skinning, indexed colour palettes, sprite sheets and tilemap support. Used by indie game developers worldwide.',
    tags: ['Pixel Art', 'Animation', 'Sprite'],
    tagsBlue: ['Indie Dev', 'Game Assets'],
    price: 'Rs. 350',
    recommended: true,
    link: 'https://www.aseprite.org/',
    linkLabel: 'Official Site'
  },
  {
    id: 'blockbench',
    category: 'art-design',
    name: 'Blockbench',
    version: 'v5.0.7',
    icon: 'assets/tool/software/art-design/blockbench.png',
    desc: 'Free 3D modelling tool built for low-poly and block-style assets. Perfect for Minecraft mods, indie game models and stylised characters. Exports to major formats and game engines.',
    tags: ['3D', 'Free', 'Low-Poly'],
    tagsBlue: ['Minecraft', 'Game Models'],
    price: 'Free',
    recommended: false,
    link: 'https://www.blockbench.net/',
    linkLabel: 'Official Site'
  },
  {
    id: 'fotojet',
    category: 'art-design',
    name: 'FotoJet Designer',
    version: 'v1.4.5',
    icon: 'assets/tool/software/art-design/fotojet.png',
    desc: 'Graphic design tool with templates for posters, cards, social posts and collages. Drag-and-drop interface with built-in clipart, fonts and backgrounds. Good for quick designs.',
    tags: ['Design', 'Templates', 'Posters'],
    tagsBlue: ['Collage'],
    price: 'Rs. 150',
    recommended: false,
    link: '',
    linkLabel: 'Get Tool'
  },
  {
    id: 'gimp',
    category: 'art-design',
    name: 'GIMP',
    version: 'v3.0.8',
    icon: 'assets/tool/software/art-design/gimp.png',
    desc: 'Powerful free photo editor and image manipulation tool. Layers, masks, filters, curves, clone stamp and much more. The open-source alternative to Photoshop for serious image work.',
    tags: ['Photo Editor', 'Free', 'Open Source'],
    tagsBlue: ['Layers', 'Filters'],
    price: 'Free',
    recommended: false,
    link: 'https://www.gimp.org/downloads/',
    linkLabel: 'Official Site'
  },
  {
    id: 'krita',
    category: 'art-design',
    name: 'Krita',
    version: 'v5.2.15',
    icon: 'assets/tool/software/art-design/krita.png',
    desc: 'Professional digital painting software built for artists. Natural brush engine, stabilisers, animation timeline, comic panels and HDR support. Designed for concept art and illustration.',
    tags: ['Digital Art', 'Free', 'Painting'],
    tagsBlue: ['Animation', 'Illustration'],
    price: 'Free',
    recommended: true,
    link: 'https://krita.org/en/download/',
    linkLabel: 'Official Site'
  },
  {
    id: 'drawio',
    category: 'art-design',
    name: 'draw.io',
    version: 'v14.9.6',
    icon: 'assets/tool/software/art-design/drawio.png',
    desc: 'Free diagram and flowchart maker. Create wireframes, network diagrams, org charts, UML diagrams and mind maps. Works offline and exports to PNG, SVG, PDF and more.',
    tags: ['Diagrams', 'Free', 'Flowcharts'],
    tagsBlue: ['UML', 'Wireframe'],
    price: 'Free',
    recommended: false,
    link: 'https://www.drawio.com/',
    linkLabel: 'Official Site'
  },
  {
    id: 'vectorian',
    category: 'art-design',
    name: 'Vectorian Giotto',
    version: 'Installer',
    icon: 'assets/tool/software/art-design/vectorian.png',
    desc: 'Legacy Flash-style animation tool for creating vector animations and interactive content. Discontinued but still functional for retro animation projects and learning purposes.',
    tags: ['Animation', 'Vector', 'Legacy'],
    tagsBlue: ['Flash-Style'],
    price: 'Free',
    recommended: false,
    link: '',
    linkLabel: 'Get Tool'
  },

  /* ─── DEVELOPMENT & CODING ─── */
  {
    id: 'git',
    category: 'dev-coding',
    name: 'Git',
    version: 'v2.53.0.2',
    icon: 'assets/tool/software/dev-coding/git.png',
    desc: "The world's most used version control system. Track changes, manage branches, collaborate with teams and push to GitHub or GitLab. Essential tool for every developer.",
    tags: ['Version Control', 'CLI', 'Essential'],
    tagsBlue: ['GitHub', 'GitLab'],
    price: 'Free',
    recommended: true,
    link: 'https://git-scm.com/downloads',
    linkLabel: 'Official Site'
  },
  {
    id: 'gradle',
    category: 'dev-coding',
    name: 'Gradle',
    version: 'v7.3',
    icon: 'assets/tool/software/dev-coding/gradle.png',
    desc: 'Powerful build automation tool for Java, Kotlin and Android projects. Handles dependencies, compiling, testing and packaging. Widely used with Android Studio and IntelliJ IDEA.',
    tags: ['Build Tool', 'Java', 'Android'],
    tagsBlue: ['Kotlin', 'Automation'],
    price: 'Free',
    recommended: false,
    link: 'https://gradle.org/install/',
    linkLabel: 'Official Site'
  },
  {
    id: 'mcreator',
    category: 'dev-coding',
    name: 'MCreator',
    version: 'v2022.2',
    icon: 'assets/tool/software/dev-coding/mcreator.png',
    desc: 'Visual Minecraft mod creator — no deep Java knowledge required. Design mobs, items, blocks, dimensions and structures with a GUI. Great for learning modding and game development basics.',
    tags: ['Minecraft', 'Mod Dev', 'Visual'],
    tagsBlue: ['Java Mods', 'Beginner'],
    price: 'Free',
    recommended: false,
    link: 'https://mcreator.net/',
    linkLabel: 'Official Site'
  },
  {
    id: 'notepadpp',
    category: 'dev-coding',
    name: 'Notepad++',
    version: 'v8.4.9',
    icon: 'assets/tool/software/dev-coding/notepadpp.png',
    desc: 'Lightweight but powerful code and text editor for Windows. Syntax highlighting for 80+ languages, multi-tab editing, macros, plugins and find-and-replace across files.',
    tags: ['Text Editor', 'Free', 'Lightweight'],
    tagsBlue: ['Syntax Highlight', 'Plugins'],
    price: 'Free',
    recommended: false,
    link: 'https://notepad-plus-plus.org/downloads/',
    linkLabel: 'Official Site'
  },
  {
    id: 'python',
    category: 'dev-coding',
    name: 'Python',
    version: 'v3.14.3',
    icon: 'assets/tool/software/dev-coding/python.png',
    desc: 'The most popular general-purpose programming language. Ideal for scripting, automation, web development, data science, AI and game development. Massive library ecosystem via pip.',
    tags: ['Language', 'Scripting', 'AI'],
    tagsBlue: ['pip', 'Automation'],
    price: 'Free',
    recommended: true,
    link: 'https://www.python.org/downloads/',
    linkLabel: 'Official Site'
  },
  {
    id: 'tednotepad',
    category: 'dev-coding',
    name: 'TED Notepad',
    version: 'v6.3.1',
    icon: 'assets/tool/software/dev-coding/tednotepad.png',
    desc: 'Ultra-lightweight plain text editor for Windows. Zero distractions, no formatting, portable — perfect for quick notes, config file editing and minimal writing without any overhead.',
    tags: ['Text Editor', 'Portable', 'Minimal'],
    tagsBlue: ['Lightweight'],
    price: 'Free',
    recommended: false,
    link: '',
    linkLabel: 'Get Tool'
  },
  {
    id: 'vscode',
    category: 'dev-coding',
    name: 'Visual Studio Code',
    version: 'v1.109.2',
    icon: 'assets/tool/software/dev-coding/vscode.png',
    desc: "The most popular code editor in the world. Built-in Git, IntelliSense, extensions marketplace, debugger, terminal and live share. Supports every language and framework out there.",
    tags: ['Code Editor', 'Free', 'Extensions'],
    tagsBlue: ['IntelliSense', 'Debugger'],
    price: 'Free',
    recommended: true,
    link: 'https://code.visualstudio.com/download',
    linkLabel: 'Official Site'
  },
  {
    id: 'java',
    category: 'dev-coding',
    name: 'Java JRE',
    version: '8u51',
    icon: 'assets/tool/software/dev-coding/java.png',
    desc: 'Java Runtime Environment 8 — required to run Java-based applications including Minecraft, MCreator, legacy tools and many enterprise apps. The most compatible Java version for older software.',
    tags: ['Runtime', 'Java 8', 'Essential'],
    tagsBlue: ['Minecraft', 'Legacy Apps'],
    price: 'Free',
    recommended: false,
    link: 'https://www.java.com/en/download/',
    linkLabel: 'Official Site'
  },
  {
    id: 'nsis',
    category: 'dev-coding',
    name: 'NSIS / NSIS7z',
    version: 'v3.11 / v19.00',
    icon: 'assets/tool/software/dev-coding/nsis.png',
    desc: 'NSIS (Nullsoft Scriptable Install System) — create professional Windows installers. NSIS7z adds 7-Zip compression support for smaller, faster setup packages. Used for distributing Windows software.',
    tags: ['Installer Builder', 'Windows', 'Packaging'],
    tagsBlue: ['7z Compression'],
    price: 'Free',
    recommended: false,
    link: 'https://nsis.sourceforge.io/Download',
    linkLabel: 'Official Site'
  },

  /* ─── UTILITIES & DRIVERS ─── */
  {
    id: '7zip',
    category: 'utilities',
    name: '7-Zip',
    version: 'v26.00',
    icon: 'assets/tool/software/utilities/7zip.png',
    desc: 'The best free file archiver. Opens ZIP, RAR, 7z, TAR, ISO and 40+ more formats. 7z format offers the best compression ratio. Lightweight, fast and works from right-click context menu.',
    tags: ['Archiver', 'Free', 'Essential'],
    tagsBlue: ['7z', 'ZIP', 'RAR'],
    price: 'Free',
    recommended: true,
    link: 'https://www.7-zip.org/download.html',
    linkLabel: 'Official Site'
  },
  {
    id: 'anydesk',
    category: 'utilities',
    name: 'AnyDesk',
    version: 'Latest Installer',
    icon: 'assets/tool/software/utilities/anydesk.png',
    desc: 'Fast and secure remote desktop tool. Access your PC from anywhere, share your screen or provide remote support. Low latency connection even on slow networks.',
    tags: ['Remote Desktop', 'Support'],
    tagsBlue: ['Screen Share'],
    price: 'Rs. 200',
    recommended: false,
    link: 'https://anydesk.com/en/downloads/windows',
    linkLabel: 'Official Site'
  },
  {
    id: 'easeus',
    category: 'utilities',
    name: 'EaseUS Disk',
    version: 'Latest',
    icon: 'assets/tool/software/utilities/easeus.png',
    desc: 'Disk management and data recovery suite. Recover lost files, clone drives, manage partitions and back up data. Useful for system migrations and recovering from accidental deletions.',
    tags: ['Disk Tool', 'Recovery', 'Backup'],
    tagsBlue: ['Partition', 'Clone'],
    price: 'Rs. 300',
    recommended: false,
    link: '',
    linkLabel: 'Get Tool'
  },
  {
    id: 'partitionwizard',
    category: 'utilities',
    name: 'Partition Wizard',
    version: 'x86/64',
    icon: 'assets/tool/software/utilities/partitionwizard.png',
    desc: 'Professional disk partition manager. Resize, merge, split, format and convert partitions without data loss. Migrate OS to SSD, recover lost partitions and manage disk space easily.',
    tags: ['Partition', 'Disk Manager'],
    tagsBlue: ['SSD Migration', 'Recovery'],
    price: 'Rs. 200',
    recommended: false,
    link: '',
    linkLabel: 'Get Tool'
  },
  {
    id: 'ffmpeg',
    category: 'utilities',
    name: 'FFmpeg',
    version: 'v8.0.1',
    icon: 'assets/tool/software/utilities/ffmpeg.png',
    desc: 'The ultimate command-line multimedia framework. Convert, stream, record and process video and audio in any format. Powers hundreds of apps behind the scenes. Essential for developers and power users.',
    tags: ['CLI', 'Convert', 'Essential'],
    tagsBlue: ['Video', 'Audio', 'Dev Tool'],
    price: 'Free',
    recommended: false,
    link: 'https://ffmpeg.org/download.html',
    linkLabel: 'Official Site'
  },
  {
    id: 'flux',
    category: 'utilities',
    name: 'f.lux',
    version: 'Latest Installer',
    icon: 'assets/tool/software/utilities/flux.png',
    desc: 'Screen colour temperature adjuster that reduces blue light at night. Automatically warms your display after sunset to reduce eye strain and help you sleep better.',
    tags: ['Eye Care', 'Night Mode', 'Free'],
    tagsBlue: ['Blue Light Filter'],
    price: 'Free',
    recommended: false,
    link: 'https://justgetflux.com/',
    linkLabel: 'Official Site'
  },
  {
    id: 'idm',
    category: 'utilities',
    name: 'Internet Download Manager',
    version: 'v6.42.58',
    icon: 'assets/tool/software/utilities/idm.png',
    desc: "The most popular download accelerator for Windows. Splits downloads into segments for maximum speed, resumes broken downloads, integrates with all major browsers and has a built-in scheduler.",
    tags: ['Downloader', 'Accelerator'],
    tagsBlue: ['Browser Integration', 'Resume'],
    price: 'Rs. 350',
    recommended: true,
    link: '',
    linkLabel: 'Get Tool'
  },
  {
    id: 'irfanview',
    category: 'utilities',
    name: 'IrfanView',
    version: 'v4.73',
    icon: 'assets/tool/software/utilities/irfanview.png',
    desc: 'Blazing-fast image viewer and basic editor for Windows. Opens virtually every image format, supports batch conversion, basic editing, slideshow and thumbnail browsing.',
    tags: ['Image Viewer', 'Free', 'Fast'],
    tagsBlue: ['Batch Convert'],
    price: 'Free',
    recommended: false,
    link: 'https://www.irfanview.com/main_download_engl.htm',
    linkLabel: 'Official Site'
  },
  {
    id: 'klite',
    category: 'utilities',
    name: 'K-Lite Codec Pack',
    version: 'v19.5.5',
    icon: 'assets/tool/software/utilities/klite.png',
    desc: 'Complete collection of audio and video codecs for Windows. Fixes playback issues for MKV, AVI, HEVC and obscure formats. Includes Media Player Classic for a clean, fast media player.',
    tags: ['Codecs', 'Free', 'Media'],
    tagsBlue: ['MKV', 'HEVC', 'MPC'],
    price: 'Free',
    recommended: false,
    link: '',
    linkLabel: 'Get Tool'
  },
  {
    id: 'netlimiter',
    category: 'utilities',
    name: 'NetLimiter',
    version: 'v5.3.26',
    icon: 'assets/tool/software/utilities/netlimiter.png',
    desc: 'Internet traffic control and monitoring tool. Limit bandwidth per app, block internet access for specific programs, monitor real-time usage and set data transfer quotas.',
    tags: ['Network', 'Bandwidth', 'Monitor'],
    tagsBlue: ['Per-App Control'],
    price: 'Rs. 250',
    recommended: false,
    link: '',
    linkLabel: 'Get Tool'
  },
  {
    id: 'poweriso',
    category: 'utilities',
    name: 'PowerISO',
    version: 'v9.0',
    icon: 'assets/tool/software/utilities/poweriso.png',
    desc: 'All-in-one ISO tool — create, edit, extract, burn and mount ISO/BIN/NRG/DAA disc image files. Create bootable USB drives from ISO files. Essential for OS installs and disc images.',
    tags: ['ISO Tool', 'Burn', 'Mount'],
    tagsBlue: ['Bootable USB'],
    price: 'Rs. 200',
    recommended: false,
    link: '',
    linkLabel: 'Get Tool'
  },
  {
    id: 'revo',
    category: 'utilities',
    name: 'Revo Uninstaller Pro',
    version: 'v5.x',
    icon: 'assets/tool/software/utilities/revo.png',
    desc: 'Advanced program uninstaller that removes leftover files, registry entries and folders that normal uninstallers miss. Keeps your system clean and prevents software clutter buildup.',
    tags: ['Uninstaller', 'Registry', 'Cleaner'],
    tagsBlue: ['Deep Clean'],
    price: 'Rs. 250',
    recommended: false,
    link: '',
    linkLabel: 'Get Tool'
  },
  {
    id: 'rufus',
    category: 'utilities',
    name: 'Rufus',
    version: 'v3.21',
    icon: 'assets/tool/software/utilities/rufus.png',
    desc: "The fastest and most reliable bootable USB creator. Flash Windows, Linux or any ISO to a USB drive in minutes. Supports GPT/MBR, UEFI/BIOS and NTFS/FAT32. Totally free and portable.",
    tags: ['Bootable USB', 'Free', 'Portable'],
    tagsBlue: ['Windows Install', 'Linux'],
    price: 'Free',
    recommended: true,
    link: 'https://rufus.ie/en/',
    linkLabel: 'Official Site'
  },
  {
    id: 'sumatrapdf',
    category: 'utilities',
    name: 'SumatraPDF',
    version: 'v3.5.2',
    icon: 'assets/tool/software/utilities/sumatrapdf.png',
    desc: 'Minimal, super fast PDF reader for Windows. Also opens EPUB, MOBI, XPS and comic book formats. No toolbars, no bloat — just instant file opening and clean reading.',
    tags: ['PDF Reader', 'Free', 'Fast'],
    tagsBlue: ['EPUB', 'Portable'],
    price: 'Free',
    recommended: false,
    link: 'https://www.sumatrapdfreader.org/download-free-pdf-viewer',
    linkLabel: 'Official Site'
  },
  {
    id: 'vlc',
    category: 'utilities',
    name: 'VLC Media Player',
    version: 'v3.0.23',
    icon: 'assets/tool/software/utilities/vlc.png',
    desc: "The world's most popular free media player. Plays everything — MKV, MP4, AVI, FLV, DVD, Blu-ray and streams. No codecs needed, works on any file. Essential on every PC.",
    tags: ['Media Player', 'Free', 'Essential'],
    tagsBlue: ['All Formats', 'Streaming'],
    price: 'Free',
    recommended: true,
    link: 'https://www.videolan.org/vlc/',
    linkLabel: 'Official Site'
  },
  {
    id: 'winrar',
    category: 'utilities',
    name: 'WinRAR',
    version: 'v7.20',
    icon: 'assets/tool/software/utilities/winrar.png',
    desc: 'Classic archive manager for Windows. Create and extract RAR, ZIP, 7z and many other formats. Powerful compression, password protection, repair broken archives and split large files.',
    tags: ['Archiver', 'RAR', 'ZIP'],
    tagsBlue: ['Password Protect', 'Split'],
    price: 'Rs. 200',
    recommended: false,
    link: '',
    linkLabel: 'Get Tool'
  },
  {
    id: 'thorium',
    category: 'utilities',
    name: 'Thorium Browser',
    version: 'SSE3 Installer',
    icon: 'assets/tool/software/utilities/thorium.png',
    desc: 'Chromium-based browser optimised for maximum speed. Compiled with advanced CPU flags for faster JavaScript, page loads and media. A drop-in Chrome replacement with better performance.',
    tags: ['Browser', 'Chromium', 'Fast'],
    tagsBlue: ['SSE3', 'Optimised'],
    price: 'Free',
    recommended: false,
    link: 'https://thorium.rocks/',
    linkLabel: 'Official Site'
  },
  {
    id: 'directx',
    category: 'utilities',
    name: 'DirectX',
    version: 'Jun2010 Runtime',
    icon: 'assets/tool/software/utilities/directx.png',
    desc: 'Microsoft DirectX June 2010 End-User Runtime. Installs legacy DirectX 9/10 components required by older PC games and applications. Fixes "d3dx" missing DLL errors instantly.',
    tags: ['Runtime', 'Gaming', 'DirectX'],
    tagsBlue: ['Legacy Games', 'DLL Fix'],
    price: 'Free',
    recommended: false,
    link: '',
    linkLabel: 'Get Tool'
  },
  {
    id: 'vcredist',
    category: 'utilities',
    name: 'Visual C++ Redist',
    version: '2015–2022 Pack',
    icon: 'assets/tool/software/utilities/vcredist.png',
    desc: 'Microsoft Visual C++ Redistributable all-in-one pack for 2015 to 2022. Required by thousands of programs and games. Fixes "VCRUNTIME" and "MSVCP" missing DLL errors in one install.',
    tags: ['Runtime', 'DLL Fix', 'Essential'],
    tagsBlue: ['All-in-One', 'Games'],
    price: 'Free',
    recommended: false,
    link: '',
    linkLabel: 'Get Tool'
  },

  /* ─── PC PERFORMANCE & SECURITY ─── */
  {
    id: 'bitdefender',
    category: 'pc-security',
    name: 'Bitdefender',
    version: 'v27 (64-bit)',
    icon: 'assets/tool/software/pc-security/bitdefender.png',
    desc: 'Top-rated antivirus and internet security suite. Real-time threat detection, ransomware protection, web filtering and minimal system impact. Consistently ranked #1 in independent AV tests.',
    tags: ['Antivirus', 'Security', '64-bit'],
    tagsBlue: ['Real-Time Protection', 'Ransomware'],
    price: 'Rs. 400',
    recommended: true,
    link: '',
    linkLabel: 'Get Tool'
  },
  {
    id: 'driverbooster',
    category: 'pc-security',
    name: 'Driver Booster',
    version: 'Latest Installer',
    icon: 'assets/tool/software/pc-security/driverbooster.png',
    desc: 'Automatic driver updater by IObit. Scans your system, finds outdated drivers and updates them safely. Fixes hardware issues, improves game performance and keeps your PC stable.',
    tags: ['Drivers', 'Update', 'IObit'],
    tagsBlue: ['Auto Update', 'Gaming'],
    price: 'Rs. 200',
    recommended: false,
    link: '',
    linkLabel: 'Get Tool'
  },
  {
    id: 'iobit',
    category: 'pc-security',
    name: 'IObit Malware Fighter',
    version: 'Latest Installer',
    icon: 'assets/tool/software/pc-security/iobit.png',
    desc: 'Advanced malware and spyware remover with real-time protection. Deep scan engine detects trojans, ransomware and PUPs that regular antivirus misses. Works alongside your main AV.',
    tags: ['Malware', 'Security', 'IObit'],
    tagsBlue: ['Spyware', 'Ransomware'],
    price: 'Rs. 200',
    recommended: false,
    link: '',
    linkLabel: 'Get Tool'
  },
  {
    id: 'memreduct',
    category: 'pc-security',
    name: 'MemReduct',
    version: 'v3.5.2',
    icon: 'assets/tool/software/pc-security/memreduct.png',
    desc: 'Lightweight real-time RAM management tool. Monitor memory usage, manually or automatically free RAM, reduce standby list and keep your system running smooth on low-RAM machines.',
    tags: ['RAM', 'Memory', 'Free'],
    tagsBlue: ['Lightweight', 'Real-Time'],
    price: 'Free',
    recommended: false,
    link: '',
    linkLabel: 'Get Tool'
  },
  {
    id: 'quickcpu',
    category: 'pc-security',
    name: 'QuickCPU',
    version: 'Latest Installer',
    icon: 'assets/tool/software/pc-security/quickcpu.png',
    desc: 'CPU performance optimiser and power plan manager. Fine-tune processor speed, core parking, power saving modes and thermal management. Get the most performance from your CPU.',
    tags: ['CPU', 'Performance', 'Optimiser'],
    tagsBlue: ['Power Plan', 'Thermal'],
    price: 'Free',
    recommended: false,
    link: '',
    linkLabel: 'Get Tool'
  },
  {
    id: 'smadav',
    category: 'pc-security',
    name: 'Smadav Pro',
    version: 'v15.5 (2025)',
    icon: 'assets/tool/software/pc-security/smadav.png',
    desc: 'Indonesian antivirus with strong USB flash drive protection. Works as a secondary antivirus alongside your main AV. Specialises in detecting USB-spread viruses common in Southeast Asia.',
    tags: ['Antivirus', 'USB Protection', 'Pro'],
    tagsBlue: ['Secondary AV', 'SEA'],
    price: 'Rs. 150',
    recommended: false,
    link: '',
    linkLabel: 'Get Tool'
  },
  {
    id: 'smartdefrag',
    category: 'pc-security',
    name: 'Smart Defrag',
    version: 'Latest Installer',
    icon: 'assets/tool/software/pc-security/smartdefrag.png',
    desc: 'Fast disk defragmentation tool by IObit. Automatically defrag HDDs in the background, optimise file placement for faster boot and load times. HDD users only — not for SSDs.',
    tags: ['Defrag', 'HDD', 'IObit'],
    tagsBlue: ['Auto Mode', 'Boot Defrag'],
    price: 'Free',
    recommended: false,
    link: '',
    linkLabel: 'Get Tool'
  },
  {
    id: 'smartgamebooster',
    category: 'pc-security',
    name: 'Smart Game Booster',
    version: 'Latest Installer',
    icon: 'assets/tool/software/pc-security/smartgamebooster.png',
    desc: 'One-click PC gaming optimiser. Stops background processes, frees RAM, adjusts power plan and cleans temp files before you game. Shows CPU/GPU/RAM temps while playing.',
    tags: ['Game Booster', 'FPS', 'Optimiser'],
    tagsBlue: ['RAM Free', 'Temps Monitor'],
    price: 'Rs. 150',
    recommended: false,
    link: '',
    linkLabel: 'Get Tool'
  },
  {
    id: 'privadovpn',
    category: 'pc-security',
    name: 'PrivadoVPN',
    version: 'Latest Installer',
    icon: 'assets/tool/software/pc-security/privadovpn.png',
    desc: 'Zero-log VPN with fast servers and a generous free tier. Encrypts your connection, hides your IP and bypasses geo-restrictions. Swiss-based provider with strong privacy standards.',
    tags: ['VPN', 'Privacy', 'Free Tier'],
    tagsBlue: ['Zero Log', 'Swiss'],
    price: 'Free',
    recommended: false,
    link: 'https://privadovpn.com/download/',
    linkLabel: 'Official Site'
  },

  /* ─── STUDENT, OFFICE & APPS ─── */
  {
    id: 'libreoffice',
    category: 'office-apps',
    name: 'LibreOffice',
    version: 'v25.8.4',
    icon: 'assets/tool/software/office-apps/libreoffice.png',
    desc: 'Full free office suite — Writer, Calc, Impress, Draw, Base and Math. Fully compatible with Microsoft Office formats. The best free alternative to MS Office for students and everyday use.',
    tags: ['Office', 'Free', 'Open Source'],
    tagsBlue: ['Word', 'Excel', 'Slides'],
    price: 'Free',
    recommended: true,
    link: 'https://www.libreoffice.org/download/libreoffice/',
    linkLabel: 'Official Site'
  },
  {
    id: 'accessruntime',
    category: 'office-apps',
    name: 'MS Access Runtime',
    version: '2024 Runtime',
    icon: 'assets/tool/software/office-apps/accessruntime.png',
    desc: 'Microsoft Access Runtime lets you run Access database applications without a full Office licence. Required for database-driven tools and forms built in Microsoft Access.',
    tags: ['Database', 'Runtime', 'Microsoft'],
    tagsBlue: ['Access DB'],
    price: 'Free',
    recommended: false,
    link: '',
    linkLabel: 'Get Tool'
  },
  {
    id: 'notion',
    category: 'office-apps',
    name: 'Notion',
    version: 'v7.2.1',
    icon: 'assets/tool/software/office-apps/notion.png',
    desc: 'All-in-one workspace for notes, databases, tasks and wikis. Build personal dashboards, project boards, study notes and team docs. Flexible blocks system lets you organise anything.',
    tags: ['Notes', 'Productivity', 'Desktop'],
    tagsBlue: ['Database', 'Wiki'],
    price: 'Free',
    recommended: true,
    link: 'https://www.notion.so/desktop',
    linkLabel: 'Official Site'
  },
  {
    id: 'scratch',
    category: 'office-apps',
    name: 'Scratch',
    version: 'v3.29.1',
    icon: 'assets/tool/software/office-apps/scratch.png',
    desc: 'Visual block-based programming for beginners and kids. Create interactive stories, games and animations by snapping code blocks together. Made by MIT — used in schools worldwide.',
    tags: ['Education', 'Coding', 'Kids'],
    tagsBlue: ['Visual Coding', 'MIT'],
    price: 'Free',
    recommended: false,
    link: 'https://scratch.mit.edu/download',
    linkLabel: 'Official Site'
  },
  {
    id: 'telegram',
    category: 'office-apps',
    name: 'Telegram',
    version: 'v6.4.1',
    icon: 'assets/tool/software/office-apps/telegram.png',
    desc: 'Fast, secure and feature-rich messaging app. Send messages, files, photos and videos. Create groups, channels and bots. Known for privacy, speed and large file sharing up to 2GB.',
    tags: ['Messaging', 'Desktop', 'Secure'],
    tagsBlue: ['Channels', 'Bots', 'File Share'],
    price: 'Free',
    recommended: false,
    link: 'https://desktop.telegram.org/',
    linkLabel: 'Official Site'
  },
  {
    id: 'tmnations',
    category: 'office-apps',
    name: 'TM Nations Forever',
    version: 'Original Setup',
    icon: 'assets/tool/software/office-apps/tmnations.png',
    desc: 'Free classic racing game by Nadeo. High-speed track racing with a built-in level editor, online multiplayer and a huge community track library. A legendary freeware game from the 2000s.',
    tags: ['Game', 'Racing', 'Free'],
    tagsBlue: ['Classic', 'Multiplayer'],
    price: 'Free',
    recommended: false,
    link: '',
    linkLabel: 'Get Tool'
  },
  {
    id: 'tuxpaint',
    category: 'office-apps',
    name: 'TuxPaint',
    version: 'v0.9.35',
    icon: 'assets/tool/software/office-apps/tuxpaint.png',
    desc: 'Award-winning free drawing program for young children ages 3–12. Fun sound effects, stamps, magic tools and a simple canvas. A safe, screen-friendly creative tool for kids.',
    tags: ['Kids', 'Drawing', 'Education'],
    tagsBlue: ['Ages 3-12', 'Free'],
    price: 'Free',
    recommended: false,
    link: 'https://tuxpaint.org/download/',
    linkLabel: 'Official Site'
  },
  {
    id: 'tuxtype',
    category: 'office-apps',
    name: 'TuxType',
    version: 'v1.8.1',
    icon: 'assets/tool/software/office-apps/tuxtype.png',
    desc: 'Fun typing tutor game for kids featuring Tux the Linux penguin. Improve typing speed and accuracy through engaging mini-games and lessons. Great for school and home learning.',
    tags: ['Typing', 'Kids', 'Education'],
    tagsBlue: ['Typing Game', 'Free'],
    price: 'Free',
    recommended: false,
    link: '',
    linkLabel: 'Get Tool'
  },
  {
    id: 'sinhalatamil',
    category: 'office-apps',
    name: 'Sinhala Tamil IME',
    version: 'Latest Installer',
    icon: 'assets/tool/software/office-apps/sinhalatamil.png',
    desc: 'Input Method Editor for typing in Sinhala and Tamil scripts on Windows. Enables native language keyboard input across all apps — documents, browsers and messaging. Essential for Sri Lankan users.',
    tags: ['Language', 'Sinhala', 'Tamil'],
    tagsBlue: ['IME', 'Sri Lanka'],
    price: 'Free',
    recommended: false,
    link: '',
    linkLabel: 'Get Tool'
  }

];

/* ── STATS (auto-calculated) ── */
window.TOOL_STATS = (function () {
  var catalog = window.TOOL_CATALOG || [];
  var cats = new Set(catalog.map(function (t) { return t.category; }));
  return {
    totalTools: catalog.length,
    totalCategories: cats.size,
    recommended: catalog.filter(function (t) { return t.recommended; }).length
  };
})();
